# Form implementation generated from reading ui file 'register.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1193, 832)
        font = QtGui.QFont()
        font.setPointSize(18)
        Dialog.setFont(font)
        self.label = QtWidgets.QLabel(parent=Dialog)
        self.label.setGeometry(QtCore.QRect(290, 30, 231, 71))
        font = QtGui.QFont()
        font.setPointSize(25)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(parent=Dialog)
        self.label_2.setGeometry(QtCore.QRect(290, 100, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.txtTen = QtWidgets.QTextEdit(parent=Dialog)
        self.txtTen.setGeometry(QtCore.QRect(600, 160, 251, 41))
        self.txtTen.setObjectName("txtTen")
        self.txtContact = QtWidgets.QTextEdit(parent=Dialog)
        self.txtContact.setGeometry(QtCore.QRect(290, 220, 561, 41))
        self.txtContact.setObjectName("txtContact")
        self.txtPassword = QtWidgets.QTextEdit(parent=Dialog)
        self.txtPassword.setGeometry(QtCore.QRect(290, 280, 561, 41))
        self.txtPassword.setObjectName("txtPassword")
        self.txtHo = QtWidgets.QTextEdit(parent=Dialog)
        self.txtHo.setGeometry(QtCore.QRect(290, 160, 281, 41))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.txtHo.setFont(font)
        self.txtHo.setObjectName("txtHo")
        self.label_3 = QtWidgets.QLabel(parent=Dialog)
        self.label_3.setGeometry(QtCore.QRect(290, 390, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.QSpinBox = QtWidgets.QComboBox(parent=Dialog)
        self.QSpinBox.setGeometry(QtCore.QRect(290, 450, 111, 31))
        self.QSpinBox.setObjectName("QSpinBox")
        self.QComboBox = QtWidgets.QComboBox(parent=Dialog)
        self.QComboBox.setGeometry(QtCore.QRect(480, 450, 101, 31))
        self.QComboBox.setObjectName("QComboBox")
        self.QSpinBox_2 = QtWidgets.QComboBox(parent=Dialog)
        self.QSpinBox_2.setGeometry(QtCore.QRect(690, 450, 101, 31))
        self.QSpinBox_2.setObjectName("QSpinBox_2")
        self.label_4 = QtWidgets.QLabel(parent=Dialog)
        self.label_4.setGeometry(QtCore.QRect(290, 500, 261, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.radioNam = QtWidgets.QRadioButton(parent=Dialog)
        self.radioNam.setGeometry(QtCore.QRect(290, 570, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioNam.setFont(font)
        self.radioNam.setObjectName("radioNam")
        self.radioNu = QtWidgets.QRadioButton(parent=Dialog)
        self.radioNu.setGeometry(QtCore.QRect(470, 570, 95, 20))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.radioNu.setFont(font)
        self.radioNu.setObjectName("radioNu")
        self.label_5 = QtWidgets.QLabel(parent=Dialog)
        self.label_5.setGeometry(QtCore.QRect(290, 560, 581, 181))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setWordWrap(True)
        self.label_5.setObjectName("label_5")
        self.chkAgree = QtWidgets.QCheckBox(parent=Dialog)
        self.chkAgree.setGeometry(QtCore.QRect(290, 720, 381, 20))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.chkAgree.setFont(font)
        self.chkAgree.setObjectName("chkAgree")
        self.txtConfirm = QtWidgets.QTextEdit(parent=Dialog)
        self.txtConfirm.setGeometry(QtCore.QRect(290, 350, 561, 41))
        self.txtConfirm.setObjectName("txtConfirm")
        self.btnRegister = QtWidgets.QPushButton(parent=Dialog)
        self.btnRegister.setGeometry(QtCore.QRect(440, 760, 161, 41))
        self.btnRegister.setObjectName("btnRegister")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "Đăng ký "))
        self.label_2.setText(_translate("Dialog", "Nhanh chóng đăng ký dễ dàng"))
        self.txtTen.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:10pt;\">Tên</span></p></body></html>"))
        self.txtContact.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Số di động hoặc Email</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p></body></html>"))
        self.txtPassword.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Mật khẩu mới</span></p></body></html>"))
        self.txtHo.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Họ</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:11pt;\"><br /></p></body></html>"))
        self.label_3.setText(_translate("Dialog", "Ngày sinh"))
        self.label_4.setText(_translate("Dialog", "Giới tính"))
        self.radioNam.setText(_translate("Dialog", "Nam"))
        self.radioNu.setText(_translate("Dialog", "Nữ"))
        self.label_5.setText(_translate("Dialog", "Bằng cách nhấp vào Đăng ký, bạn đồng ý với Điều khoản, Chính sách dữ liệu và Chính sách cookie của chúng tôi. Bạn có thể nhận được thông báo của chúng tôi qua SMS và hủy nhận bất kỳ lúc nào."))
        self.chkAgree.setText(_translate("Dialog", "CheckBoxTôi đồng ý với các điều khoản trên"))
        self.txtConfirm.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:18pt; font-weight:400; font-style:normal;\">\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:11pt;\">Xác nhận MK</span></p></body></html>"))
        self.btnRegister.setText(_translate("Dialog", "Đăng ký"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
