# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(767, 666)
        self.btnThem = QtWidgets.QPushButton(parent=Dialog)
        self.btnThem.setGeometry(QtCore.QRect(600, 180, 101, 31))
        self.btnThem.setObjectName("btnThem")
        self.btnSua = QtWidgets.QPushButton(parent=Dialog)
        self.btnSua.setGeometry(QtCore.QRect(600, 230, 101, 31))
        self.btnSua.setObjectName("btnSua")
        self.btnXoa = QtWidgets.QPushButton(parent=Dialog)
        self.btnXoa.setGeometry(QtCore.QRect(600, 280, 101, 31))
        self.btnXoa.setObjectName("btnXoa")
        self.btnHienThi = QtWidgets.QPushButton(parent=Dialog)
        self.btnHienThi.setGeometry(QtCore.QRect(600, 330, 101, 31))
        self.btnHienThi.setObjectName("btnHienThi")
        self.btnTim_2 = QtWidgets.QPushButton(parent=Dialog)
        self.btnTim_2.setGeometry(QtCore.QRect(600, 380, 101, 31))
        self.btnTim_2.setObjectName("btnTim_2")
        self.tableNhanSu = QtWidgets.QTabWidget(parent=Dialog)
        self.tableNhanSu.setGeometry(QtCore.QRect(110, 160, 481, 341))
        self.tableNhanSu.setObjectName("tableNhanSu")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.txtCCCD = QtWidgets.QLineEdit(parent=self.tab)
        self.txtCCCD.setGeometry(QtCore.QRect(10, 50, 171, 21))
        self.txtCCCD.setObjectName("txtCCCD")
        self.txtHoTen = QtWidgets.QLineEdit(parent=self.tab)
        self.txtHoTen.setGeometry(QtCore.QRect(10, 10, 171, 21))
        self.txtHoTen.setObjectName("txtHoTen")
        self.txtNgaySinh = QtWidgets.QLineEdit(parent=self.tab)
        self.txtNgaySinh.setGeometry(QtCore.QRect(320, 10, 151, 21))
        self.txtNgaySinh.setObjectName("txtNgaySinh")
        self.txtGioiTinh = QtWidgets.QLineEdit(parent=self.tab)
        self.txtGioiTinh.setGeometry(QtCore.QRect(320, 60, 91, 21))
        self.txtGioiTinh.setObjectName("txtGioiTinh")
        self.txtDiaChi = QtWidgets.QLineEdit(parent=self.tab)
        self.txtDiaChi.setGeometry(QtCore.QRect(10, 90, 211, 21))
        self.txtDiaChi.setObjectName("txtDiaChi")
        self.tableNhanSu.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.txtTim = QtWidgets.QLineEdit(parent=self.tab_2)
        self.txtTim.setGeometry(QtCore.QRect(10, 10, 231, 21))
        self.txtTim.setObjectName("txtTim")
        self.btnTim = QtWidgets.QPushButton(parent=self.tab_2)
        self.btnTim.setGeometry(QtCore.QRect(10, 50, 81, 31))
        self.btnTim.setObjectName("btnTim")
        self.tableNhanSu.addTab(self.tab_2, "")

        self.retranslateUi(Dialog)
        self.tableNhanSu.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.btnThem.setText(_translate("Dialog", "Thêm"))
        self.btnSua.setText(_translate("Dialog", "Sửa"))
        self.btnXoa.setText(_translate("Dialog", "Xóa"))
        self.btnHienThi.setText(_translate("Dialog", "HienThi"))
        self.btnTim_2.setText(_translate("Dialog", "Tìm"))
        self.tableNhanSu.setTabText(self.tableNhanSu.indexOf(self.tab), _translate("Dialog", "Quản lý nhân sự"))
        self.btnTim.setText(_translate("Dialog", "Tìm"))
        self.tableNhanSu.setTabText(self.tableNhanSu.indexOf(self.tab_2), _translate("Dialog", "Danh sách"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec())
